create table if not exists public.content(
 id bigint generated by default as identity primary key,
 category text not null, topic text not null, title text not null,
 answer text not null, language text default 'as',
 owner_id uuid references auth.users(id), created_at timestamptz default now()
);
create index if not exists content_category_topic_idx on public.content(category,topic);
alter table public.content enable row level security;
drop policy if exists "public read content" on public.content;
create policy "public read content" on public.content for select using (true);
-- Do NOT create public INSERT/UPDATE/DELETE policies.
-- After creating your private owner Auth account, create owner-only policies:
-- INSERT/UPDATE/DELETE must require auth.uid() = owner_id.
